export default defineAppConfig({
  nuxtIcon: {
    aliases: {
      spinner: 'fa6-solid:spinner',
      brand: 'carbon:code',
      experimental: 'ph:flask-fill',
      webworker: 'el:cogs',
      mdn: 'simple-icons:mozilla',
      chrome: 'logos:chrome',
      permission: 'bx:check-shield',
      secure: 'bxs:lock-alt',
      unsecure: 'bxs:lock-open-alt',
      external: 'ci:external-link',
      search: 'carbon:search',
      clear: 'carbon:erase',
      light: 'ph:sun',
      dark: 'ph:moon',
      system: 'ph:circle-half',
      charging: 'akar-icons:battery-charging',
      batteryEmpty: 'akar-icons:battery-empty',
      batteryLow: 'akar-icons:battery-low',
      batteryMedium: 'akar-icons:battery-medium',
      batteryFull: 'akar-icons:battery-full',
      width: 'ant-design:column-width-outlined',
      height: 'ant-design:column-height-outlined',
      location: 'carbon:airport-location',
      interaction: 'icon-park-solid:click',
      encryption: 'carbon:encryption',
      vibration: 'ph:vibrate',
      share: 'ph-share-network-fill',
      fullscreen: 'ph:arrows-out-simple',
      eyedropper: 'ph:eyedropper-sample-duotone',
      pwa: 'logos:pwa',
      vercel: 'akar-icons:vercel-fill',
      downlink: 'carbon:cloud-download',
      roundtrip: 'carbon:arrows-horizontal',
      grid: 'bi:grid-3x3-gap-fill',
      list: 'ph:rows-fill',
      available: 'akar-icons:circle-check',
      unavailable: 'akar-icons:circle-x',
      email: 'ph:paper-plane-tilt',
      discussion: 'ph:chats',
      check: 'ph:check-bold',
      cross: 'ph:x-bold',
    },
  },
})
