export default defineAppConfig({
  nuxtIcon: {
    aliases: {
      spinner: 'fa6-solid:spinner',
      brand: 'carbon:code',
      experimental: 'fa6-solid:flask-vial',
      webworker: 'el:cogs',
      mdn: 'simple-icons:mozilla',
      chrome: 'logos:chrome',
      permission: 'bx:check-shield',
      secure: 'bxs:lock-alt',
      unsecure: 'bxs:lock-open-alt',
      external: 'ci:external-link',
      search: 'carbon:search',
      clear: 'carbon:erase',
      light: 'carbon:sun',
      dark: 'carbon:moon',
      system: 'carbon:contrast',
      charging: 'akar-icons:battery-charging',
      batteryEmpty: 'akar-icons:battery-empty',
      batteryLow: 'akar-icons:battery-low',
      batteryMedium: 'akar-icons:battery-medium',
      batteryFull: 'akar-icons:battery-full',
      width: 'ant-design:column-width-outlined',
      height: 'ant-design:column-height-outlined',
      location: 'carbon:airport-location',
      interaction: 'icon-park-solid:click',
      encryption: 'carbon:encryption',
      vibration: 'ph:vibrate',
      share: 'ph-share-network-fill',
      fullscreen: 'ph:arrows-out-simple',
      eyedropper: 'ph:eyedropper-sample-duotone',
    },
  }
})
